### ISSUE TITLE
if the user messages twice then the app crashes

### ISSUE THREAD

**Issue by Majboor** [faetalize/zodiac#27]
Uncaught (in promise) Error: [400 ] Please ensure that multiturn requests ends with a user role or a function response.
    at E (index.mjs:66:1)
    at async A (index.mjs:99:1)

**Comment by Majboor** [comment]
This is due to google not supporting multiturn requests to avoid this, implementation of hiding the send button until there is a response is best, due to the multiturn requests error I think the app also crashes random loadings, I tried some times

**Comment by faetalize** [comment]
yes, good catch. will be fixed in the next release (v0.1.4). coming up next week

**Comment by faetalize** [comment]
fixed

**Comment by Majboor** [comment]
did you happen to add chat history yet?
